clickvisual/clickvisual

.all-contributorsrc
README-CN.md
README.md

@all-contributors please add @sevennt  for code

add all-contributors

---

api/internal/apiv1/inquiry/inquiry.go
api/pkg/model/db/index.go

[fix: index query](https://github.com/shimohq/mogo/commit/cd20d9c386dfa1f4d8695f0344e0788f1f99a10e)

fix: index query

---

api/internal/apiv1/inquiry/inquiry.go
api/pkg/model/db/index.go
ui/config/config.ts
ui/package.json
ui/src/models/dataLogs.ts
ui/src/pages/DataLogs/components/RawLogList/LogItem/LogContentParse/index.tsx
ui/src/pages/DataLogs/components/RawLogList/LogItem/index.less
ui/src/pages/document.ejs
ui/src/services/dataLogs.ts
ui/src/services/systemSetting.ts
ui/yarn.lock

fix: Optimized front-end packaging
fix: Fix the URL path problem of the interface
docs: index only support json

Optimized front-end compilation and fixed index configuration issues

---

api/internal/apiv1/configure/base.go
api/internal/service/inquiry/clickhouse.go
api/internal/service/inquiry/template.go

[log->_log_](https://github.com/shimohq/mogo/commit/cb889d2f980d2d492b68feb53dad09b10993c266)

log->_log_

---

ui/src/models/dataLogs.ts
ui/src/pages/DataLogs/components/DateTimeSelected/CustomTimeInterval/index.tsx
ui/src/pages/DataLogs/components/DateTimeSelected/DateTimeSelectedCard/index.tsx
ui/src/pages/DataLogs/components/DateTimeSelected/RelativeTime/index.tsx
ui/src/pages/DataLogs/components/HighCharts/index.tsx
ui/src/pages/DataLogs/components/RawLogTabs/index.tsx
ui/src/pages/DataLogs/components/RawLogsIndexes/IndexItem/index.tsx

[fix: Fix log viewing error](https://github.com/shimohq/mogo/commit/e31c4b1641cdffdbd7ac7b6e53e98cc6cbe2d98b)

fix: Fix log viewing error

---

ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/pages/DataLogs/components/RawLogList/LogItem/LogContentParse/index.tsx
ui/src/pages/DataLogs/components/RawLogList/LogItem/LogItemDetails/index.tsx
ui/src/pages/DataLogs/components/RawLogsIndexes/IndexItem/index.less
ui/src/pages/DataLogs/components/RawLogsIndexes/IndexItem/index.tsx

fix: add index desc 
fix: null -> empty 
fix: index analysis use null value to replace empty string

Some front-end display optimizations

---

data/prometheus/prom2click-deployment.yaml
data/prometheus/prom2click-service.yaml
data/prometheus/prometheus-configmap.yaml

Signed-off-by: kl7sn <mex7.0828@gmail.com>

docs: yaml

---

api/internal/apiv1/alarm/alarm.go
api/internal/apiv1/base/database.go
api/internal/apiv1/base/table.go
api/internal/apiv1/sys/instance.go
api/internal/router/router.go
api/internal/service/alarm.go
api/internal/service/instance.go
api/pkg/constx/errors.go
api/pkg/model/db/instance.go
api/pkg/model/view/database.go
scripts/migration/latest.sql
ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/pages/SystemSetting/InstancePanel/components/CreatedOrUpdatedInstanceModal/index.tsx

[fix: alarm store error](https://github.com/shimohq/mogo/commit/bfe238cbd2337aabef27c64edaaf66f19702897a)[](https://github.com/kl7sn)

fix: alarm store error 

---

api/internal/apiv1/alarm/alarm.go
api/internal/router/router.go
data/all-in-one/alertmanager/alertmanager.yaml
docker-compose.m1.yml
docker-compose.yml

[fix: config.d->conf.d](https://github.com/shimohq/mogo/commit/3c7c7024c85dab1935181ab168dde96c2ba93400)

fix: config.d->conf.d

---

api/internal/apiv1/alarm/alarm.go
api/internal/apiv1/alarm/webhook.go
api/internal/router/router.go
data/all-in-one/alertmanager/alertmanager.yaml
data/all-in-one/mogo/config/resource.yaml
docker-compose.m1.yml
docker-compose.yml

fix: Defining user types
fix: add rule menu
fix: webhook api 
fix: docker compose add mock process

fix some problem

---

api/internal/apiv1/base/view.go
api/internal/service/inquiry/core.go
api/internal/service/inquiry/core_test.go
ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/DatabaseViewsDraw/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/ModalCreatedLogLibrary/NewTable/index.tsx

[fix: the request parameter contains an and that causes the request to…](https://github.com/shimohq/mogo/commit/708a8e730f31eb116ac5aebff00b1d8d7da77676)

fix: the request parameter contains an and

---

api/internal/service/inquiry/core.go
api/internal/service/inquiry/core_test.go

[feat: support "xx and aa" in query value](https://github.com/shimohq/mogo/commit/c2ce443f7123235cb73c581c79c97e4b51a54668)

feat: support "xx and aa" in query value

---

api/internal/apiv1/base/view.go
api/internal/service/alertmanager/dingding.go
api/internal/service/inquiry/clickhouse.go
api/internal/service/inquiry/core.go
api/internal/service/inquiry/core_test.go
api/pkg/model/db/alarm.go
go.mod
go.sum
ui/src/hooks/useTimeUnits.ts

[feat: dingding alert link add timestamp](https://github.com/shimohq/mogo/commit/2c81a49d2b423634e14a4320a59bddc378be0075)

feat: dingding alert link add timestamp

---

data/all-in-one/mogo/config/docker.toml

[fix: writer_timeou -> writer_timeout](https://github.com/shimohq/mogo/commit/4bde002bb48d566881bf6fcb4557274be241337d)

fix: writer_timeou -> writer_timeout

---

api/internal/apiv1/alarm/alarm.go
api/internal/apiv1/base/table.go
api/internal/service/alarm.go
api/internal/service/inquiry/builder/builder.go
api/internal/service/inquiry/clickhouse.go
api/internal/service/inquiry/core.go
api/pkg/constx/common.go
api/pkg/model/db/alarm.go
api/pkg/model/view/table.go
data/all-in-one/mogo/config/docker.toml
docs/1.2 domain.md
ui/src/components/IconFont/index.tsx
ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/models/datalogs/useLogLibraryViews.ts
ui/src/pages/Alarm/Rules/components/AlarmHistory/HistoryBorad/index.tsx
ui/src/pages/Alarm/Rules/components/AlarmHistory/HistoryOptions/index.tsx
ui/src/pages/Alarm/Rules/components/AlarmHistory/index.less
ui/src/pages/Alarm/Rules/components/AlarmHistory/index.tsx
ui/src/pages/Alarm/Rules/components/AlarmInfoDraw/index.less
ui/src/pages/Alarm/Rules/components/AlarmInfoDraw/index.tsx
ui/src/pages/Alarm/Rules/components/FormAlarmDraw/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/DatabaseViewsDraw/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/LogLibraryInfoDraw/index.less
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/LogLibraryInfoDraw/index.tsx
ui/src/pages/DataLogs/components/SelectedDatabaseDraw/index.tsx
ui/src/pages/SystemSetting/ClustersPanel/components/ClustersTable/index.tsx
ui/src/pages/SystemSetting/InstancePanel/components/InstanceTable/index.tsx
ui/src/services/alarm.ts

fix: 修复 build 后前端白屏问题
feat: alarm overview page modification, log library details and alarm… 
feat: the alarm data storage policy adjustment is supported

the alarm data storage policy adjustment is supported

---

api/internal/apiv1/alarm/alarm.go
api/internal/apiv1/base/table.go
api/pkg/model/view/alarm.go
api/pkg/model/view/table.go

[feat: added alarm details info](https://github.com/shimohq/mogo/commit/fa33eddb197fd72fd4f3acedb65059168f1bc808)

feat: added alarm details info

---

api/internal/service/alarm.go
api/internal/service/alertmanager/dingding.go
api/internal/service/inquiry/builder/builder.go
api/internal/service/inquiry/builder/builder_test.go
api/internal/service/inquiry/builder/bumo/model.go
api/internal/service/inquiry/builder/director.go
api/internal/service/inquiry/builder/standalone/data.go
api/internal/service/inquiry/builder/standalone/stream.go
api/internal/service/inquiry/builder/standalone/view.go
api/internal/service/inquiry/clickhouse.go
api/internal/service/inquiry/core.go
api/pkg/constx/common.go
api/pkg/model/db/table.go

[feat: builder model & add exist table with any engine](https://github.com/shimohq/mogo/commit/6974903db2096aa53086119257612c45d01dc063)

feat: builder model & add exist table with any engine

---

api/internal/service/event/user.go

[fix: import mdp/pkg/model/db](https://github.com/shimohq/mogo/commit/6d2922cc9f0c033d21c5c8db277bea6b90432330)[](https://github.com/kl7sn)

fix: import mdp/pkg/model/db 

---

api/internal/apiv1/base/database.go
api/internal/apiv1/base/table.go
api/internal/apiv1/setting/instance.go
api/internal/service/event/view.go
api/pkg/model/db/base.go
api/pkg/model/view/database.go
api/pkg/model/view/sys.go
ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/pages/DataLogs/components/SelectedDatabaseDraw/CreatedDatabaseModal/index.tsx
ui/src/pages/DataLogs/components/SelectedDatabaseDraw/index.tsx
ui/src/pages/SystemSetting/InstancePanel/components/CreatedOrUpdatedInstanceModal/index.tsx
ui/src/pages/SystemSetting/InstancePanel/components/InstanceTable/index.tsx
ui/src/services/dataLogs.ts
ui/src/services/systemSetting.ts

feat: Add Add Cluster properties for instance, add select cluster pro… 
feat: Cluster mode supports front-end completion

Cluster mode supports front-end completion

---

Makefile
api/internal/router/router.go
ui/config/config.ts
ui/src/pages/User/Login/Footer/index.tsx
ui/src/services/alarm.ts
ui/src/services/configure.ts
ui/src/services/dataLogs.ts
ui/src/services/install.ts
ui/src/services/menu.ts
ui/src/services/systemSetting.ts
ui/src/services/users.ts

[feat: Subpath configuration support](https://github.com/shimohq/mogo/commit/6efda50c10c6387e3dc617cd7d1318c6e7dee487)

feat: Subpath configuration support

---

api/internal/apiv1/base/database.go

[fix: Cluster database create overtime](https://github.com/shimohq/mogo/commit/680f9a01d920f9cde8dff2a91600b9e05bdd7b87)[](https://github.com/kl7sn)

fix: Cluster database create overtime 

---

api/internal/apiv1/base/database.go

[fix: Cluster database create fail](https://github.com/shimohq/mogo/commit/f374c40e3f1e078a23ca42e6c65cba1d8eb59c73)[](https://github.com/kl7sn)

fix: Cluster database create failure

---

api/internal/apiv1/user/user.go

[feat: Add demo mode](https://github.com/shimohq/mogo/commit/a1d125eee0fc8f07dda9a897110fea4141c1107c)

feat: Add demo mode

---

ui/config/proxy.ts
ui/config/routes.ts
ui/package.json
ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/models/events.ts
ui/src/pages/SystemSetting/Events/EventList/index.tsx
ui/src/pages/SystemSetting/Events/Operations/index.tsx
ui/src/pages/SystemSetting/Events/index.less
ui/src/pages/SystemSetting/Events/index.tsx
ui/src/services/events.ts
ui/yarn.lock

feat: Added the Event Center page

---

.gitignore
api/internal/apiv1/base/table.go
api/internal/service/inquiry/builder/cluster/view.go
api/internal/service/inquiry/builder/standalone/view.go
api/internal/service/inquiry/clickhouse.go
api/internal/service/inquiry/core.go
config/resource.yaml
ui/config/proxy.ts
ui/src/models/dataLogs.ts
ui/src/models/users.ts
ui/src/pages/DataLogs/components/DataSourceMenu/ModalCreatedLogLibrary/LocalTable/index.tsx

fix: Add event router
fix: table name include - support
feat: Record the database modification records

feat: Record the database modification records

---

api/internal/apiv1/alarm/alarm.go
api/internal/apiv1/base/database.go
api/internal/apiv1/base/table.go
api/internal/service/alarm.go
api/internal/service/inquiry/clickhouse.go
api/internal/service/inquiry/core.go
api/pkg/constx/errors.go

fix: Fix the table deletion failure in cluster mode

fix: Fix the table deletion failure in cluster mode

---

api/internal/apiv1/alarm/alarm.go
api/internal/apiv1/base/table.go
api/internal/router/router.go
api/internal/service/parser.go
api/pkg/model/db/alarm.go
api/pkg/model/db/database.go
api/pkg/model/db/table.go
api/pkg/utils/time.go
ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/pages/Alarm/Rules/components/AlarmTable/index.tsx

style: The display of the alarm list page is optimized
refactor: Optimization of dynamic time interval calculation

refactor: Optimization of dynamic time interval calculation

---

api/internal/service/inquiry/clickhouse.go

feat: Support uint32 and uint64 as time field type
fix: Use toDateTime form DateTime search

Use toDateTime form DateTime search

---

api/internal/apiv1/base/table.go
api/internal/service/inquiry/builder/cluster/data.go
api/pkg/model/db/table.go
api/pkg/model/view/table.go
ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts

fix: ReplicatedMergeTree grammar mistakes
feat: Table desc field

fix: ReplicatedMergeTree grammar mistakes

---

ui/src/models/dataLogs.ts
ui/src/models/datalogs/useLogPanes.ts
ui/src/pages/Alarm/Rules/components/AlarmHistory/HistoryBorad/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/LogLibraryItem/index.tsx
ui/src/pages/DataLogs/components/DateTimeSelected/CustomTimeInterval/index.tsx
ui/src/pages/DataLogs/components/DateTimeSelected/DateTimeSelectedCard/index.tsx
ui/src/pages/DataLogs/components/DateTimeSelected/RelativeTime/index.tsx
ui/src/pages/DataLogs/components/HighCharts/index.tsx
ui/src/pages/DataLogs/components/RawLogList/LogItem/LogItemDetails/index.tsx
ui/src/pages/DataLogs/components/RawLogTabs/index.tsx
ui/src/pages/DataLogs/components/RawLogs/index.tsx
ui/src/pages/DataLogs/components/RawLogsIndexes/IndexItem/index.tsx
ui/src/pages/DataLogs/components/RawLogsIndexes/index.tsx
ui/src/pages/DataLogs/components/RawLogsOperations/index.tsx
ui/src/pages/DataLogs/components/SearchBar/index.tsx
ui/src/pages/DataLogs/components/SelectedDatabaseDraw/index.tsx
ui/src/pages/DataLogs/hooks/useLogUrlParams.ts
ui/src/pages/DataLogs/hooks/useTimeOptions.ts
ui/src/pages/DataLogs/index.tsx

1.Optimized the log label switching function
2.Url parameters are saved in the database

fix(LogTab/UrlParams):

---

api/internal/apiv1/base/table.go
api/internal/service/inquiry/clickhouse.go
api/internal/service/inquiry/core.go
api/internal/service/instance.go

The graph shows the error throw

The graph shows the error throw

---

api/internal/apiv1/base/table.go
api/internal/service/inquiry/clickhouse.go
api/internal/service/instance.go
api/pkg/model/db/index.go
api/pkg/model/view/inquiry.go
ui/src/components/JsonView/JsonStringValue/index.tsx
ui/src/config/config.ts
ui/src/services/events.ts

[feat: Optimize query speed by using hash functions](https://github.com/shimohq/mogo/commit/abf1e33a7b8b82dc664903cd0a5dcc64c52ecad2)

feat: Optimize query speed by using hash functions

---

api/internal/apiv1/base/table.go
api/internal/service/index.go
api/internal/service/inquiry/clickhouse.go
api/internal/service/inquiry/clickhouse_test.go
api/pkg/model/db/index.go
api/pkg/model/view/setting.go
api/pkg/model/view/table.go

[feat: String transfer hash function after conversion storage](https://github.com/shimohq/mogo/commit/733f4cc294063ff89babf516bc4f63382a0a9761)

feat: String transfer hash function after conversion storage

---

ui/src/config/config.ts
ui/src/models/datalogs/types.ts
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/LogLibraryInfoDraw/index.less
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/LogLibraryInfoDraw/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/LogLibraryItem/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/index.less
ui/src/pages/DataLogs/components/DataSourceMenu/SearchLogLibrary/index.tsx
ui/src/pages/DataLogs/components/RawLogList/LogItem/index.less
ui/src/services/dataLogs.ts
ui/src/styles/var.less

1.Optimize the log library list
2.Added log library description

feat(log library): Optimize the log library

---

ui/package.json
ui/yarn.lock

[fix: yarn build](https://github.com/shimohq/mogo/commit/ae3670c8b8bcc01ca1e3ce2826b5e9803d64c790)

fix: yarn build

---

api/internal/apiv1/base/instance.go
api/internal/router/router.go
api/internal/service/permission/checkeruser.go
api/pkg/model/db/alarm.go
ui/src/pages/SystemSetting/Pms/Role/components/RootUserForm/index.tsx
ui/src/pages/SystemSetting/Pms/Role/components/UserSelect/index.tsx
ui/src/pages/SystemSetting/Pms/Role/hooks/useConsole.tsx
ui/src/pages/SystemSetting/Pms/Role/index.tsx
ui/src/services/pms.ts

[fix: Alarm list 500](https://github.com/shimohq/mogo/commit/c248454eeb25e4314cdfcf44584bead5999f373c)
[fix: Fix the root permission data update delay problem](https://github.com/shimohq/mogo/commit/3fc15de6c2892a1c3db9b0dd5be5e10fcb5560b8)

fix: Fix the root permission data update delay problem

---

config/default.toml
data/all-in-one/clickvisual/config/docker.toml
data/all-in-one/clickvisual/config/rbac.conf
data/all-in-one/migration/database.sql

[fix: docker-compose standalone](https://github.com/clickvisual/clickvisual/commit/b26fab848fc5a766915098245fd0be9d52d1c3f7)

fix: docker-compose standalone

---

.github/workflows/docker.yml
api/internal/apiv1/configure/base.go

[set docker/setup-qemu-action@v2](https://github.com/clickvisual/clickvisual/commit/c0521bc0a4d40444e901f393ccc5cbbf3e45a123)

set docker/setup-qemu-action@v2

---

api/pkg/model/db/configure.go

fix: LockAt datetime to bigint

---

api/internal/service/configure/configure.go
api/internal/service/inquiry/clickhouse.go
api/pkg/model/db/configure.go

[fix: Int or float data may lost](https://github.com/clickvisual/clickvisual/commit/311102962a9cb9509a6adc17a05cf47a56313d96)

fix: Int or float data may lost

---

api/internal/apiv1/base/database.go
api/internal/apiv1/base/table.go
api/internal/router/router.go
api/pkg/model/db/database.go
api/pkg/model/view/database.go

[feat: Add database and table update API](https://github.com/clickvisual/clickvisual/commit/f64ebd6a382061edf21ec2c88fa51d64c49d970a)

feat: Add database and table update API

---

ui/config/config.ts
ui/package.json
ui/src/components/JsonView/JsonData/index.tsx
ui/src/components/JsonView/JsonStringValue/index.tsx
ui/src/components/JsonView/JsonValue/index.tsx
ui/src/components/JsonView/index.less
ui/src/components/JsonView/types.ts
ui/src/models/dataLogs.ts
ui/src/models/datalogs/useLogLibrary.ts
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogContent/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogContentParse/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogItemDetails/index.tsx
ui/src/pages/SystemSetting/InstancePanel/components/RoleAssign/components/RolesList/CollapseItem/CollapseTitle/index.tsx
ui/src/pages/SystemSetting/InstancePanel/components/RoleAssign/components/RolesList/CollapseItem/GrantList/index.tsx
ui/src/pages/SystemSetting/Role/components/UserSelect/index.tsx
ui/yarn.lock

1.Log highlighting supports secondary indexes
2.Remove WebPack shards
3.Update the umi version

feat(data logs): Log highlighting supports secondary indexes

---

api/internal/apiv1/alarm/alarm.go
api/internal/service/alarm.go
api/pkg/model/view/alarm.go

[feat: Added the returned contents of alarm list data](https://github.com/clickvisual/clickvisual/commit/6c396d61e964650c341fbf5ca58947b4c9e810d9)

feat: Added the returned contents of alarm list data

---

api/internal/apiv1/alarm/alarm.go
api/internal/apiv1/alarm/alertmanager.go
api/internal/apiv1/base/database.go
api/internal/service/alarm.go
api/internal/service/alertmanager.go
api/pkg/model/db/alarm.go
api/pkg/model/view/alarm.go
api/pkg/model/view/database.go
api/pkg/push/dingding.go

[refactor: Alarm content optimization](https://github.com/clickvisual/clickvisual/commit/2b6fa95d13e24e95d6158a706f506946e7d0dfee)

refactor: Alarm content optimization

---

api/internal/apiv1/base/table.go

fix: Table API alias info

---

ui/src/components/BreadCrumbs/index.tsx
ui/src/components/BreadCrumbs/type.ts
ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/models/dataLogs.ts
ui/src/models/datalogs/types.ts
ui/src/models/datalogs/useLogLibrary.ts
ui/src/pages/Alarm/Rules/components/AlarmTable/index.tsx
ui/src/pages/Alarm/Rules/styles/index.less
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/EditLogLibraryModal/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/LogLibraryInfoDraw/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/LogLibraryItem/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/SourceHeader/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/index.tsx
ui/src/pages/DataLogs/components/RawLogTabs/index.tsx
ui/src/pages/DataLogs/components/SelectedDatabaseDraw/EditDatabaseModel/index.tsx
ui/src/pages/DataLogs/components/SelectedDatabaseDraw/index.tsx
ui/src/pages/DataLogs/hooks/useLogUrlParams.ts
ui/src/pages/DataLogs/index.tsx
ui/src/pages/DataLogs/styles/index.less
ui/src/pages/SystemSetting/InstancePanel/components/CreatedOrUpdatedInstanceModal/index.tsx
ui/src/pages/SystemSetting/InstancePanel/components/InstanceTable/index.tsx
ui/src/services/dataLogs.ts

[Database list items expand by default]

feat: Breadcrumb navigation was added for instances, databases, and log libraries

---

README.md
api/internal/router/router.go
api/internal/service/inquiry/clickhouse.go
api/pkg/model/db/table.go

[docs: tks & friends](https://github.com/clickvisual/clickvisual/commit/758c80565cb177378b5e9eb47fc4c94f7e860b64)

docs: tks & friends

---

ui/src/pages/Alarm/Rules/components/FormAlarmDraw/QueryStatisticsItem/CreatedAndUpdatedModal/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/ModalCreatedLogLibrary/LocalTable/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogItemDetails/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogItemOperation/MoreLog/MoreLogPopoverContent/index.tsx
ui/src/pages/DataLogs/hooks/useLogUrlParams.ts

fix(alarm): 修复数据库显示 id

---

ui/config/defaultSettings.ts
ui/src/components/JsonView/JsonData/index.tsx
ui/src/components/JsonView/JsonStringValue/index.tsx
ui/src/components/JsonView/JsonValue/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogContent/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogItemDetails/LogItemDetailsContent/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogItemFold/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/index.less
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/index.tsx
ui/src/pages/DataLogs/hooks/useLogItemDetail.ts
ui/src/styles/var.less

feat(data logs): 日志折叠 v1.0

---

ui/src/pages/Alarm/Rules/components/AlarmTable/index.tsx
ui/src/pages/Alarm/Rules/components/FormAlarmDraw/QueryStatisticsItem/CreatedAndUpdatedModal/index.tsx
ui/src/pages/Alarm/Rules/components/Operations/index.tsx

fix: The alarm creation process was optimized

---

ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogItemFold/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/index.less
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/index.tsx
ui/src/pages/DataLogs/hooks/useLogItemDetail.ts

feat(log data): Index field query is supported after collapse, fix #316

---

ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/models/dataLogs.ts
ui/src/models/datalogs/useLogLibrary.ts
ui/src/models/datalogs/useLogSwitch.ts
ui/src/pages/DataLogs/components/BreadcrumbNavigation/NvaRight/index.tsx
ui/src/pages/DataLogs/components/BreadcrumbNavigation/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/EditLogLibraryModal/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/index.tsx
ui/src/pages/DataLogs/hooks/useLogListScroll.ts
ui/src/pages/DataLogs/styles/index.less

feat(log data):  The switch determines whether the histogram is displayed, fix #321

---

ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogItemDetails/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogItemFold/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogItemOperation/CopyLog/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogItemOperation/MoreLog/MoreLogPopoverContent/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogItemOperation/MoreLog/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogItemOperation/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/index.tsx
ui/src/pages/DataLogs/utils/LogItemDetail.ts

fix(log data): Log list click pagination to expand data and list data inconsistency repair

---

api/internal/apiv1/alarm/alertmanager.go
api/internal/router/router.go
api/internal/service/alertmanager.go
ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/models/alarms/useChannel.ts
ui/src/pages/Alarm/Notifications/components/CreateChannelModal/index.tsx
ui/src/services/alarm.ts

Used to check whether the new channel is available after configuration

add send test button to CreateChannelModal

---

api/internal/service/alertmanager.go

feat(api alert manager): Added warning information

---

config/resource.yaml
ui/config/routes.ts
ui/src/components/IconFont/index.tsx
ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/models/datalogs/useLogLibrary.ts
ui/src/pages/Alarm/Notifications/components/CreateChannelModal/index.tsx
ui/src/pages/DataAnalysis/RealTimeTrafficFlow/LibraryTree/index.tsx
ui/src/pages/DataAnalysis/RealTimeTrafficFlow/TrafficChart/TrafficChart.tsx
ui/src/pages/DataAnalysis/RealTimeTrafficFlow/TrafficChart/index.ts
ui/src/pages/DataAnalysis/RealTimeTrafficFlow/index.less
ui/src/pages/DataAnalysis/RealTimeTrafficFlow/index.tsx
ui/src/pages/DataAnalysis/TemporaryQuery/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/index.tsx
ui/src/services/dataLogs.ts

feat(route): add data analysis

---

api/internal/apiv1/base/table.go
api/internal/router/router.go
api/internal/service/inquiry/clickhouse.go
api/internal/service/inquiry/core.go
api/pkg/constx/errors.go
api/pkg/model/view/table.go

[feat: Table dependency API](https://github.com/clickvisual/clickvisual/commit/fe337371ff2766ee1a9cdd9f67f6ab86dae5f84c)
fix #324

feat: Table dependency API 

---

api/internal/apiv1/bigdata/short/folder.go
api/internal/apiv1/bigdata/short/sql.go
api/internal/router/router.go
api/pkg/model/db/alarm.go
api/pkg/model/db/base.go
api/pkg/model/db/folder.go
api/pkg/model/db/shortsql.go
api/pkg/model/view/folder.go
api/pkg/model/view/shortsql.go

feat: Bigdata short SQL API

---

docker-compose.devops.m1.yml
docker-compose.devops.yml

docs: docker compose devops

---

config/default.toml
docker-compose.devops.m1.yml
docker-compose.devops.yml

feat: Local development environment quickly set up

---

ui/src/components/JsonView/JsonData/index.tsx
ui/src/models/dataAnalysis.ts
ui/src/models/dataLogs.ts
ui/src/models/dataanalysis/useTemporaryQuery.ts
ui/src/pages/DataAnalysis/Nav/index.tsx
ui/src/pages/DataAnalysis/TemporaryQuery/components/FolderTree/CreactAndUpdateFolder/index.tsx
ui/src/pages/DataAnalysis/TemporaryQuery/components/FolderTree/index.tsx
ui/src/pages/DataAnalysis/TemporaryQuery/index.less
ui/src/pages/DataAnalysis/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogContentParse/index.tsx
ui/src/services/dataAnalysis.ts

fix: Identifies the JSON format of the log module

---

api/internal/apiv1/bigdata/node.go
api/internal/invoker/invoker.go
api/internal/router/router.go
api/internal/service/node.go
api/main.go
go.mod
go.sum

feat: Add node lock/unlock API

---

api/internal/apiv1/bigdata/node.go
api/internal/apiv1/bigdata/short/folder.go
api/internal/apiv1/bigdata/source.go
api/internal/router/router.go
api/internal/service/configure/configure.go
api/pkg/model/db/base.go
api/pkg/model/db/source.go
api/pkg/model/view/source.go

feat: Data source management for data analysis

---

api/internal/apiv1/base/instance.go
api/internal/apiv1/bigdata/folder.go
api/internal/apiv1/bigdata/mining/workflow.go
api/internal/apiv1/bigdata/node.go
api/internal/apiv1/bigdata/source.go
api/internal/invoker/invoker.go
api/internal/router/router.go
api/internal/service/bigdata/source/base.go
api/internal/service/bigdata/source/base_test.go
api/internal/service/bigdata/source/clickhouse.go
api/internal/service/bigdata/source/mysql.go
api/internal/service/install/install.go
api/pkg/model/db/base.go
api/pkg/model/db/folder.go
api/pkg/model/db/node.go
api/pkg/model/db/workflow.go
api/pkg/model/view/folder.go
api/pkg/model/view/node.go
api/pkg/model/view/source.go
api/pkg/model/view/workflow.go
go.mod
go.sum

feat: source api

---

api/internal/apiv1/base/database.go
api/pkg/model/view/base.go

fix: database list

---

api/internal/apiv1/bigdata/node.go
api/internal/service/inquiry/clickhouse.go
api/pkg/model/view/bigdata.go
ui/src/pages/DataLogs/components/DataSourceMenu/ModalCreatedLogLibrary/LocalTable/index.tsx

[fix: Folder list add primary and secondary info](https://github.com/clickvisual/clickvisual/commit/0969d5cc337a1e797f709362b48a50c49e176e0a)

fix: Folder list add primary and secondary info

---

ui/src/models/dataAnalysis.ts
ui/src/models/dataanalysis/useDataSourceManage.ts
ui/src/models/dataanalysis/useTemporaryQuery.ts
ui/src/pages/DataAnalysis/DataSourceManage/CreateAndUpdateModel/index.tsx
ui/src/pages/DataAnalysis/DataSourceManage/SearchBar/index.tsx
ui/src/pages/DataAnalysis/components/FolderTree/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/ModalCreatedLogLibrary/LocalTable/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/ModalCreatedLogLibrary/index.tsx
ui/src/pages/DataLogs/components/SelectedDatabaseDraw/index.tsx
ui/src/pages/DataLogs/hooks/useLogUrlParams.ts

fix: Add the existing log library. Switch the table and repeat the request

---

api/internal/apiv1/bigdata/node.go
api/internal/service/inquiry/clickhouse.go
api/pkg/model/view/bigdata.go
ui/src/locales/zh-CN.ts

fix: Adjustment of necessary parameters

---

api/internal/apiv1/base/table.go
api/internal/service/inquiry/clickhouse.go

logs: add debug log

---

api/internal/service/bigdata/rtsync/rtcommon.go
api/internal/service/bigdata/rtsync/rtsync_test.go
api/pkg/model/db/cluster.go

fix: Data synchronization field type mapping error

---

ui/src/pages/DataAnalysis/components/RightMenu/Results/index.tsx
ui/src/pages/DataAnalysis/components/RightMenu/VersionHistory/index.tsx

fix: Formatting unordered code

---

api/internal/apiv1/bigdata/node.go
api/internal/service/bigdata/node/tertiaryrun.go
api/internal/service/bigdata/rtsync/c2m.go
api/internal/service/bigdata/rtsync/m2c.go
api/internal/service/bigdata/rtsync/rtcommon.go
api/internal/service/inquiry/clickhouse.go
api/pkg/model/db/bigdatanode.go

[fix: RT sync cluster](https://github.com/clickvisual/clickvisual/commit/33e9694c33909eed2b3652bef7fc85b31b0a258f)

fix: RT sync cluster

---

ui/src/models/dataanalysis/useManageNodeAndFolder.ts
ui/src/pages/DataAnalysis/OfflineManager/components/WorkflowBoard/BoardChart/Board.tsx
ui/src/pages/DataAnalysis/OfflineManager/components/WorkflowBoard/BoardChart/BoardNode.tsx
ui/src/pages/DataAnalysis/OfflineManager/components/WorkflowBoard/NodeManage/indxe.tsx
ui/src/pages/DataAnalysis/components/NodeManage/ManageNodeModal.tsx
ui/src/pages/DataAnalysis/service/enums.ts
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogItemDetails/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogItemOperation/MoreLog/MoreLogPopoverContent/index.tsx
ui/src/pages/DataLogs/utils/LogItemDetail.ts

Save to detect whether there is a start and end, and do not create a start and end node

feat(workflow): Save check if there is a start and end

---

api/internal/service/depend.go
api/internal/service/depend_test.go
api/pkg/model/db/bigdatadepend.go

fix: ENGINE = Distributed parsing error

---

api/internal/apiv1/bigdata/node.go
api/internal/router/router.go
api/internal/service/node.go
api/pkg/model/view/bigdata.go

[feat: Node remote run API](https://github.com/clickvisual/clickvisual/commit/d7ea38fea5cf8ab3e90f890c640714392c97eeff)

feat: Node remote run API 

---

api/internal/apiv1/bigdata/node.go
api/internal/router/router.go
api/internal/service/bigdata/node/run.go
api/internal/service/node.go

fix: cycle import

---

api/internal/apiv1/alarm/alarm.go
api/internal/service/alarm.go
api/pkg/model/view/alarm.go

fix: Failed to read the alarm mode

---

api/internal/service/alarm.go
api/internal/service/depend.go
api/internal/service/inquiry/builder/cluster/view.go
api/internal/service/inquiry/builder/standalone/view.go
api/internal/service/inquiry/clickhouse.go
api/internal/service/inquiry/clickhouse_test.go
api/pkg/model/db/alarm.go
api/pkg/model/db/baseindex.go
api/pkg/model/db/basetable.go
api/pkg/model/db/bigdatadepend.go
ui/src/locales/zh-CN.ts
ui/src/pages/Alarm/Rules/components/FormAlarmDraw/QueryStatisticsItem/CreatedAndUpdatedModal/index.tsx

fix: Cluster mode Alarm configuration

---

api/internal/service/inquiry/clickhouse.go

fix: Alert source table remove _local

---

api/internal/apiv1/bigdata/mining/crontab.go
api/internal/service/bigdata/worker/crontab.go

feat: Node crontab stop api

---

api/internal/service/inquiry/clickhouse.go

fix: Optimize query logic

---

README-CN.md
README.md
api/internal/apiv1/base/index.go

docs: readme update

---

README.md

docs: data analysis gif url update

---

README-CN.md
README.md
api/internal/service/inquiry/clickhouse.go
ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts

fix: remove complete query limit

---

api/docs/docs.go
api/docs/swagger.json
api/docs/swagger.yaml
api/internal/apiv1/bigdata/folder.go
api/internal/apiv1/bigdata/mining/crontab.go
api/internal/apiv1/bigdata/mining/workflow.go
api/internal/apiv1/bigdata/node.go
api/internal/apiv1/bigdata/source.go
api/internal/apiv1/user/oauth.go
api/internal/apiv2/pandas/node.go
api/internal/router/router.go
api/internal/service/bigdata/worker/crontab.go
api/internal/service/event/cmdb.go
api/main.go
api/pkg/model/db/event.go
api/pkg/model/db/pandas.go
api/pkg/model/view/pandas.go

feat: Updates the action on the execution result

---

api/internal/middlewares/auth.go
api/internal/service/bigdata/node/department.go
api/pkg/model/db/pandas.go

feat: Worker support cost record

---

api/pkg/model/db/pandas.go

fix: SQL syntax error

---

api/internal/service/inquiry/clickhouse.go

fix: The time range condition priority is improved

---

api/internal/service/inquiry/clickhouse.go
api/internal/service/inquiry/clickhouse_test.go
ui/src/locales/zh-CN.ts

fix: Abnormal Hash optimization query in JOSN nested mode

---

api/internal/service/permission/pms.go
api/internal/service/permission/pmsplugin/pms.go
go.mod
go.sum

refactor: github.com/clickvisual/casbin-redis-watcher

---

api/docs/docs.go
api/docs/swagger.json
api/docs/swagger.yaml
api/internal/apiv2/storage/storage.go
api/internal/service/inquiry/builder/builder_test.go
api/internal/service/inquiry/builder/bumo/model.go
api/internal/service/inquiry/builder/cluster/stream.go
api/internal/service/inquiry/builder/common/default.go
api/internal/service/inquiry/builder/standalone/stream.go
api/internal/service/inquiry/clickhouse.go
api/internal/service/inquiry/clickhouse_test.go
api/internal/service/inquiry/core.go
api/pkg/model/view/storage.go

feat: Added the API related to storage editing

---

api/internal/service/inquiry/clickhouse.go
api/pkg/model/view/base.go

feat: Added the query takes in logs query interface

---

ui/src/components/IconFont/index.tsx
ui/src/components/UrlShareButton/index.tsx
ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/pages/DataAnalysis/DataSourceManage/SearchBar/index.tsx
ui/src/pages/DataAnalysis/StatisticalBoard/components/CompletionTask/index.tsx
ui/src/pages/DataAnalysis/StatisticalBoard/components/DashboardTop/index.tsx
ui/src/pages/DataAnalysis/StatisticalBoard/components/RunningStatus/index.tsx
ui/src/pages/DataAnalysis/StatisticalBoard/components/Screening/index.less
ui/src/pages/DataAnalysis/StatisticalBoard/components/Screening/index.tsx
ui/src/pages/DataAnalysis/StatisticalBoard/index.less
ui/src/pages/DataAnalysis/StatisticalBoard/index.tsx
ui/src/pages/DataAnalysis/TaskExecutionDetails/TaskFilter/index.less
ui/src/pages/DataAnalysis/TaskExecutionDetails/TaskFilter/index.tsx
ui/src/pages/DataAnalysis/TaskExecutionDetails/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/InstanceItem/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/LoggingLibrary/index.less
ui/src/pages/DataLogs/components/DataSourceMenu/LoggingLibrary/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/SearchLogLibrary/index.tsx
ui/src/pages/DataLogs/components/OtherSearchBar/index.tsx
ui/src/pages/DataLogs/components/SearchBar/RawLogQuery/index.tsx
ui/src/pages/DataLogs/components/SearchBar/TableQuery/index.tsx
ui/src/pages/DataLogs/index.tsx

feat: Scheduled scheduling and task details page internationalization
feat: The share button is added to the log page
feat: Optimize the structure of statistical kanban and task execution details
feat: The share button is added to the log page
feat: Optimizes the loading status of log libraries
feat: Optimize the steps to create instances when there are no instances
feat: add rel="noopener"
#566

feat: Scheduled scheduling and task details page internationalization

---

ui/src/config/config.ts
ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/pages/Alarm/Rules/components/FormAlarmDraw/QueryStatisticsItem/CreatedAndUpdatedModal/index.tsx
ui/src/pages/DataAnalysis/RealTimeBusinessFlow/components/BusinessChart/BusinessChart.tsx
ui/src/pages/DataAnalysis/RealTimeBusinessFlow/components/BusinessChart/NodeContent.tsx
ui/src/pages/DataAnalysis/RealTimeBusinessFlow/components/LibraryTree/index.tsx
ui/src/pages/DataAnalysis/RealTimeBusinessFlow/index.less
ui/src/pages/DataAnalysis/RealTimeBusinessFlow/index.tsx
ui/src/pages/DataAnalysis/TaskExecutionDetails/index.tsx
ui/src/pages/DataAnalysis/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/DatabaseItem/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/LogLibraryItem/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/LoggingLibrary/index.less
ui/src/pages/DataLogs/components/DataSourceMenu/LoggingLibrary/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogItemDetails/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogsOperations/index.tsx
ui/src/services/dataLogs.ts
ui/src/services/realTimeTrafficFlow.ts

[feat: Click Key to copy the key]
[feat: Perform time-consuming]
[feat: Logs jump to the topology]
[feat: Chinese and English formatting of topological total numbers]
[feat: Added the update time field in the topology]

feat: Overall optimization of data analysis topology

---

ui/src/components/ExportExcelButton/index.tsx
ui/src/components/IconFont/index.tsx
ui/src/components/UrlShareButton/index.tsx
ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/pages/DataAnalysis/RealTimeBusinessFlow/components/BusinessChart/NodeContent.tsx
ui/src/pages/DataAnalysis/components/RightMenu/Results/ResultsItem/index.tsx
ui/src/pages/DataAnalysis/components/RightMenu/Results/index.tsx
ui/src/pages/DataAnalysis/components/RightMenu/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/LogLibraryItem/index.tsx
ui/src/pages/DataLogs/components/SearchBar/RawLogQuery/index.tsx
ui/src/pages/DataLogs/components/SearchBar/TableQuery/index.tsx
ui/src/pages/DataLogs/components/SearchBar/index.less

feat: Optimized runtime result interaction
feat: Table icon to adjust
feat: Optimize button size

feat: Optimized runtime result interaction

---

ui/src/pages/Alarm/Rules/components/AlarmInfoDraw/index.tsx
ui/src/pages/Configure/components/Editor/index.tsx
ui/src/pages/DataAnalysis/components/RightMenu/Results/ResultsItem/index.tsx
ui/src/pages/DataAnalysis/components/RightMenu/VersionHistory/index.tsx
ui/src/pages/DataAnalysis/components/SQLEditor/EditorContent/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/EditLogLibraryModal/index.less
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/EditLogLibraryModal/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/LogLibraryInfoDraw/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/ModalCreatedLogLibrary/SelectField/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogsOperations/index.less
ui/src/pages/DataLogs/hooks/useLogUrlParams.ts

feat: The editor wraps the lines automatically
feat: Editing the log library
fix: The sharing page does not have tableList, so data acquisition cannot be triggered

feat: Editing the log library

---

api/internal/service/inquiry/clickhouse.go
api/internal/service/inquiry/clickhouse_test.go

fix: Magic function trigger condition exception fixed

---

api/internal/service/database.go

fix: nil database 500

---

api/internal/service/alertmanager.go

fix: exist table alert 500

---

ui/src/components/BreadCrumbs/index.less
ui/src/components/BreadCrumbs/index.tsx
ui/src/pages/Alarm/Rules/components/AlarmTable/index.tsx
ui/src/pages/Alarm/Rules/components/FormAlarmDraw/index.tsx

fix: The updated alarm does not contain paging information
style: Alarm list style adjusted

fix: The updated alarm does not contain paging information

---

ui/src/components/BreadCrumbs/index.less
ui/src/components/BreadCrumbs/index.tsx
ui/src/components/BreadCrumbs/type.ts
ui/src/models/dataLogs.ts
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/LogLibraryItem/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/ModalCreatedLogLibrary/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogsOperations/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/index.tsx
ui/src/pages/DataLogs/components/QueryResult/index.tsx
ui/src/pages/DataLogs/components/RawLogTabs/index.tsx
ui/src/utils/textWith.ts

feat: Separate the load states of individual pages
feat: Alarm list associated log library length calculation and adjustment
feat: If the log library fails to be added, the pop-up window is not closed #593

feat: Separate the load states of individual pages

---

ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogsOperations/SwitchLeft/HiddenFields.tsx

fix error when showing the hidden fields

fix error when showing the hidden fields

---

ui/src/app.tsx
ui/src/components/JsonView/JsonStringValue/index.tsx
ui/src/hooks/useLocalStorages.ts
ui/src/locales/zh-CN.ts
ui/src/models/dataLogs.ts
ui/src/models/dataanalysis/useIntegratedConfigs.ts
ui/src/pages/DataAnalysis/OfflineManager/components/IntegratedConfiguration/IntegratedConfigs/DataSourceModule/DatasourceSelect.tsx
ui/src/pages/DataAnalysis/OfflineManager/components/IntegratedConfiguration/index.tsx
ui/src/pages/DataAnalysis/components/RightMenu/index.less
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/LogItemDetails/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogsOperations/index.tsx
ui/src/pages/DataLogs/components/SearchBar/RawLogQuery/index.tsx
ui/src/pages/DataLogs/hooks/useLogUrlParams.ts
ui/src/services/bigDataWorkflow.ts
ui/src/services/dataLogs.ts

feat: The interface returned the first route as the redirection route
feat: If the start time and end time exist, change the time type
feat: Generate Clickhouse field maps based on mysql #602 
fix: Exclude conditional generation syntax
feat: WHERE
feat: Remove the separator =
feat: Single keyword query method added keyword highlighting

feat: Generate Clickhouse field maps based on mysql #602 

---

ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/EditLogLibraryModal/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LinkItem/LinkLogInfo/index.less
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LinkItem/LinkLogInfo/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LinkItem/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/index.tsx
ui/src/typings.d.ts
ui/src/utils/time.ts

feat: The link information bar is added
feat: Added whether the log is link when the log creation type is 3
fix: The link log format is not compliant, causing the page crash
fix: Optimized link-time conversion function and compatible with moreformats

feat: The link information bar is added

---

ui/src/components/JsonView/JsonStringValue/index.tsx
ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/models/dataLogs.ts
ui/src/models/datalogs/types.ts
ui/src/models/datalogs/useLogPanes.ts
ui/src/pages/DataLogs/components/DataSourceMenu/LogLibraryList/LogLibraryItem/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/ClickMenu/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/HighCharts/index.tsx
ui/src/pages/DataLogs/components/RawLogTabs/index.tsx
ui/src/pages/DataLogs/hooks/useLogUrlParams.ts
ui/src/services/dataLogs.ts
ui/src/utils/time.ts

feat: Histogram time unit judgment optimization
feat: When associating the link library, you can click to go to the link log library and set value as the query condition for _key

feat: When associating the link library, you can click to go to the link log library and set value as the query condition for _key

---

api/internal/service/inquiry/clickhouse.go
ui/package.json

fix DateTime64(9) search, since it will be treat as TimeFieldTypeDT

---

api/internal/service/pandas/node/secondary.go
go.mod

fix: remove import go-faster/errors

---

ui/src/components/BreadCrumbs/index.less
ui/src/components/BreadCrumbs/index.tsx
ui/src/components/BreadCrumbs/type.ts
ui/src/pages/Alarm/Rules/components/AlarmTable/index.tsx
ui/src/pages/Alarm/Rules/components/FormAlarmDraw/QueryStatisticsItem/CreatedAndUpdatedModal/index.tsx
ui/src/pages/Alarm/Rules/components/FormAlarmDraw/QueryStatisticsItem/index.less
ui/src/pages/Alarm/Rules/components/FormAlarmDraw/TriggerConditionItem/index.tsx
ui/src/pages/Alarm/Rules/components/FormAlarmDraw/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/ModalCreatedLogLibrary/LocalTable/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/ModalCreatedLogLibrary/index.tsx
ui/src/services/alarm.ts
ui/src/services/dataLogs.ts

feat: The alarm display list supports multiple tables

---

api/internal/api/apiv1/base/table.go

fix: Optimization error details returned

---

api/pkg/model/view/alarm.go
api/pkg/push/wechat.go
ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/pages/Alarm/hooks/useAlarmEnums.ts

The robot message has a length limit  Details are not shown at present

wecom robot push

---

ui/src/config/config.ts
ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/pages/Alarm/Rules/components/AlarmHistory/HistoryBorad/index.tsx
ui/src/pages/Alarm/Rules/components/AlarmHistory/index.tsx
ui/src/pages/DataLogs/components/CreateLogFilter/index.tsx
ui/src/pages/DataLogs/components/OtherSearchBar/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/HighCharts/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogsOperations/SwitchLeft/FoldingExpansionSwitch.tsx
ui/src/pages/DataLogs/components/QueryResult/FilterList/index.tsx
ui/src/pages/DataLogs/components/SearchBar/RawLogQuery/CodeMirrorSearch/index.less
ui/src/pages/DataLogs/components/SearchBar/RawLogQuery/CodeMirrorSearch/index.tsx
ui/src/pages/DataLogs/components/SearchBar/RawLogQuery/index.tsx
ui/src/pages/DataLogs/components/SearchBar/SearchBarSuffixIcon/index.less
ui/src/pages/DataLogs/components/SearchBar/index.less

fix(alarm): The page for querying alarms cannot be displayed on the alarm notification page
feat: The number of link renders was changed to 200
fix: The initial code for the table editor does not change with the filter condition
feat: The log query box is compatible with pasting multiple lines of code
feat: optimizing code closure detection
feat: repairing page logjam when special symbols exist in code
feat: Code prompt Adds the current input value as a prompt item

feat: The log query box is compatible with pasting multiple lines of code

---

ui/src/config/config.ts
ui/src/models/dataLogs.ts
ui/src/models/datalogs/types.ts
ui/src/models/datalogs/useLogPanes.ts
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/HighCharts/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogsOperations/SwitchLeft/FoldingExpansionSwitch.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogsOperations/index.tsx
ui/src/pages/DataLogs/components/SearchBar/RawLogQuery/CodeMirrorSearch/index.less
ui/src/pages/DataLogs/components/SearchBar/RawLogQuery/CodeMirrorSearch/index.tsx
ui/src/pages/DataLogs/components/SearchBar/RawLogQuery/index.tsx
ui/src/pages/DataLogs/hooks/useLogUrlParams.ts

feat: Set the number of link log requests
fix: Input box overflow problem in most cases, improve prompt timing, optimize input box performance

feat: Set the number of link log requests

---

ui/src/models/dataLogs.ts
ui/src/pages/DataLogs/components/DateTimeSelected/DateTimeSelectedCard/index.tsx
ui/src/pages/DataLogs/components/DateTimeSelected/RelativeTime/index.tsx
ui/src/pages/DataLogs/components/DateTimeSelected/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LinkItemTitle/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/index.tsx
ui/src/pages/DataLogs/components/SearchBar/RawLogQuery/index.tsx

feat(datalog): Relative time click search and close the popover
fix(share): The link style of the sharing page is inconsistent with expectations
feat(datalog): Relative time click search and close the popover
feat(linkLog): Adjust the link sequence

feat(datalog): Relative time click search and close the popover

---

ui/src/models/alarms/useAlarmOperations.ts
ui/src/pages/Alarm/Environment/components/EditEnvironmentModal/index.tsx
ui/src/pages/Alarm/Environment/index.tsx

feat(alarm): Added an alarm type operator
fix(alarm): The alarm status filter is not cached

feat(alarm): Added an alarm type operator

---

ui/src/models/dataLogs.ts
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LinkItemTitle/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogList/LogItem/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogs/index.less
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogsIndexes/IndexList/index.less
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogsIndexes/index.less
ui/src/pages/DataLogs/components/QueryResult/FilterList/index.less
ui/src/pages/DataLogs/components/QueryResult/index.less
ui/src/pages/DataLogs/components/RawLogTabs/index.less
ui/src/pages/DataLogs/components/RawLogTabs/index.tsx

fix(datalog): Log keyword highlighting matching rules are case insensitive #794 
feat: Log time conversion is compatible with more formats #803 #804
style(datalog): Log Style Adjustment (Compact) added a full-screen button #793

feat: Log page spacing is adjusted, log time is compatible with more formats, and search highlighting is case insensitive

---

ui/src/locales/en-US.ts
ui/src/locales/zh-CN.ts
ui/src/models/dataLogs.ts
ui/src/pages/DataAnalysis/components/RightMenu/VersionHistory/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogsOperations/SwitchLeft/HistogramSiwtch.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogsOperations/index.tsx
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/index.tsx
ui/src/pages/DataLogs/components/RawLogTabs/index.tsx
ui/src/pages/DataLogs/components/SearchBar/RawLogQuery/CodeMirrorSearch/WhereBox/index.less
ui/src/pages/DataLogs/components/SearchBar/RawLogQuery/CodeMirrorSearch/WhereBox/index.tsx
ui/src/pages/DataLogs/components/SearchBar/RawLogQuery/CodeMirrorSearch/index.tsx
ui/src/pages/DataLogs/components/SearchBar/RawLogQuery/index.tsx
ui/src/pages/Graphics/LinkFDG/index.tsx
ui/src/typings.d.ts
ui/src/utils/textWith.ts

feat(datalog): Input box Lenovo temporarily cancels fuzzy matching optimization performance
feat: Obtain the total number of logs from the log interface when thehistogram is not available
feat(datalog): The Favorites prompt button is added to remove the favorites prompt from the prompt #811

feat(datalog): Input box Lenovo temporarily cancels fuzzy matching optimization performance

---

ui/src/pages/DataLogs/components/SearchBar/RawLogQuery/CodeMirrorSearch/index.tsx
ui/src/pages/DataLogs/hooks/useLogUrlParams.ts

feat(datalog): The load time of the log interface does not focus on the search box
fix(url): Refreshing or entering from the url resets the url

fix(url): Refreshing or entering from the url resets the url

---

docker-compose.yml

Fix https://github.com/clickvisual/clickvisual/issues/818

fix: docker running MySQL on arm

---

api/internal/service/inquiry/clickhouse.go
api/internal/service/inquiry/databend.go
go.mod
go.sum

fix: databend chart sql

---

api/internal/api/apiv2/alert/alert.go
api/internal/service/inquiry/clickhouse.go
api/internal/service/inquiry/databend.go
api/internal/service/inquiry/factory.go
api/pkg/job/install.go
api/pkg/model/db/alarm.go
data/all-in-one/clickhouse/sql/metrics.samples.sql

Fix the new version of clickhouse does not support log alert very well

---

api/internal/router/routerv1.go
ui/src/services/dataLogs.ts

update sql query from get to post

update sql query from get to post

---

.gitignore
ui/config/proxy.ts
ui/src/pages/DataLogs/components/QueryResult/Content/RawLog/RawLogsOperations/SwitchLeft/HistogramSiwtch.tsx
ui/src/pages/DataLogs/components/SearchBar/RawLogQuery/CodeMirrorSearch/index.less
ui/src/pages/DataLogs/components/SearchBar/index.less
ui/src/pages/SystemSetting/Role/components/RootUserForm/index.tsx

修复bug
1. 权限管理root授权展示与接口不符;
2. 日志页面, 日志搜索框超宽长度时, 挤压功能按钮;
3. 日志页面, 直方图关闭后开启, 然后切换分页直方图会消失.

fix: fix bugs

---

api/internal/api/apiv1/base/instance.go
api/internal/api/apiv1/base/table.go
api/internal/api/apiv2/storage/storage.go
api/internal/pkg/model/db/factory.go
api/internal/pkg/model/view/base.go
api/internal/pkg/model/view/instance.go
api/internal/pkg/model/view/storage.go
api/internal/service/alertmanager.go
api/internal/service/inquiry/agent/agent.go
api/internal/service/inquiry/agent/agent_test.go
api/internal/service/inquiry/clickhouse/clickhouse.go
api/internal/service/inquiry/databend/databend.go
api/internal/service/inquiry/factory/factory.go
api/internal/service/instance.go
ui/src/locales/zh-CN.ts
ui/src/pages/DataLogs/components/DataSourceMenu/CreatedDatabaseModal/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/ModalCreatedLogLibrary/AgentTable/index.tsx
ui/src/pages/DataLogs/components/DataSourceMenu/ModalCreatedLogLibrary/index.tsx
ui/src/pages/SystemSetting/InstancePanel/components/CreatedOrUpdatedInstanceModal/index.tsx

Signed-off-by: kl7sn <mex7.0828@gmail.com>

feat: add agent datasource

---

api/internal/api/agent/agent.go
api/internal/pkg/agent/search/const.go
api/internal/pkg/agent/search/main.go
api/internal/pkg/agent/search/search.go
api/internal/pkg/agent/search/string.go
api/internal/pkg/agent/search/string_test.go
api/internal/pkg/cvdocker/main.go
api/internal/pkg/model/dto/agent.go
api/internal/pkg/utils/agent.go
api/internal/pkg/utils/agent_test.go
api/internal/service/inquiry/agent/agent.go

Signed-off-by: kl7sn <mex7.0828@gmail.com>

fix: GetFilterK8SContainerdWrapLog‘

---

data/helm/clickvisual/Chart.yaml
data/helm/clickvisual/templates/deployment.yaml
data/helm/clickvisual/values.yaml

Helm can't start properly, keeps showing Usage message.
update desc for chat

Fix Helm can't start properly

---

ui/src/pages/DataLogs/components/SearchBar/RawLogQuery/CodeMirrorSearch/WhereBox/index.tsx

adjust the size of Collect List

fix(ui): adjust the size of Collect List
